services:

  # Service 1: Nginx Web Server (Public-Facing Entrypoint)
  nginx:
    image: nginx:1.28.0-alpine
    restart: unless-stopped
    depends_on:
      - wordpress
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - wordpress_data:/var/www/html:ro
      - cache:/var/cache/nginx

  # Service 2: WordPress Application Server (PHP-FPM)
  wordpress:
    image: wordpress:php8.4-fpm-alpine
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: wp_
      WP_AUTO_UPDATE_CORE: "false"
      AUTOMATIC_UPDATER_DISABLED: "true"
    volumes:
      - wordpress_data:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
      - ./opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf:ro

  # Service 3: MariaDB Database Server
  mariadb:
    image: mariadb:11.8.3
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./low-memory.cnf:/etc/mysql/conf.d/low-memory.cnf:ro

volumes:
  wordpress_data:
  mariadb_data:
  cache:





